PREFIX cm: <http://comvantage.eu/graph-trans/class/m#>
PREFIX tm: <http://comvantage.eu/graph-trans/table/m#>
PREFIX c: <http://comvantage.eu/graph-trans/correspondence#>

# create table for each persistent class
# declarative 

INSERT {
	GRAPH <graph://test> {
		?t a c:Test.
	}
} WHERE {
    GRAPH <graph://correspondence> {
        [] c:c ?c, ?t;
            c:columnPrefix "".
    }
    GRAPH <graph://table> {
        ?t  a tm:Table;
            tm:name ?name.
    }
    GRAPH <graph://class> {
        ?c a cm:Class;
            cm:name ?name;
            cm:is_persistent true.
    }
}
