PREFIX cm: <http://comvantage.eu/graph-trans/class/m#>
PREFIX tm: <http://comvantage.eu/graph-trans/table/m#>
PREFIX c: <http://comvantage.eu/graph-trans/correspondence#>

# create table for each persistent class
# declarative 

INSERT {
	GRAPH <graph://test> {
		?t a :Test.
	}
WHERE {
    GRAPH <graph://correspondence> {
        [] c:c ?c, ?t;
            c:columnPrefix "".
}
